server:
  port: 8081
spring:
  application:
    name: "nexus-user-service"
  devtools:
    add-properties: false
  profiles:
    include: null
    active: "production"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "postgres"
    schema: "public"
    username: "postgres"
    password: "postgres"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
    virtual-host: "/"
    connection-timeout: 10000
    queue: "queue.user.registration"
  aws:
    s3:
      bucketName: "ariumms-gcm-s3-bucket"
      region: "us-east-1"
      endpoint: "https://s3.localhost.localstack.cloud:4566"

